config/routes.rb
Rails.application.routes.draw do



  get 'pet_wall_users/index'

  get 'pet_wall_users/show'

  get 'static_pages/welcome'

  devise_for :adopters, controllers: {
          sessions: 'adopters/sessions',
          passwords: 'adopters/passwords',
          registrations: 'adopters/registrations'
  }
  devise_for :fundations, controllers: {
          sessions: 'fundations/sessions',
          passwords: 'fundations/passwords',
          registrations: 'fundations/registrations'
  }
  get "fundations" => "static_pages#fundations"
  root to: 'static_pages#welcome'

  resources :admin_forms
  resources :pet_walls

  get "pet_wall_users" => "pet_wall_users#index"

  get "new_quertionary" => "adopters/adopter#new_quertionary"
  post "create_quertionary" => "adopters/adopter#create_quertionary"
end

app/models/adopter.rb
class Adopter < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fundation.rb
class Fundation < User
end

app/models/pet_wall.rb
class PetWall < ApplicationRecord
  has_many :pet_wall_users, class_name:"PetWallUser" , foreign_key: "pet_walls_id"
  belongs_to :winner, class_name:"User" , foreign_key: "winner_id" , optional: true
  belongs_to :user, class_name:"User" , foreign_key: "user_id"

  mount_uploader :image, ImageUploader

end

app/models/pet_wall_user.rb
class PetWallUser < ApplicationRecord
  belongs_to :user, class_name:"User" , foreign_key: "user_id"
  belongs_to :pet_walls, class_name:"PetWalls" , foreign_key: "pet_walls_id"
end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable,
         :recoverable, :rememberable, :trackable

  has_many :pet_walls_user, class_name:"PetWallUser" , foreign_key: "user_id"
  has_many :winner, class_name:"PetWall" , foreign_key: "winner_id"
  has_many :user, class_name:"PetWall" , foreign_key: "user_id"



end

app/controllers/admin_forms_controller.rb
class AdminFormsController < ApplicationController
  before_action :authenticate_fundation!#autenticador se coloca en el controlador que quieras restringir
    def index
      if fundation_signed_in?
        @admin_forms= PetWall.where(user_id:current_fundation.id)
      end
    end

    def new
      @pet_wall = PetWall.new
    end

    def edit
      find_admin_forms
      if @pet_wall == nil
        flash[:error] = "No existe el producto"
        redirect_to root_path
      end
    end

    def create
      @admin_forms.state = "No adopted"
      @admin_forms = PetWall.new(admin_forms_params)
      @admin_forms.user_id = current_fundation.id
        if @admin_forms.save!
          redirect_to admin_forms_path
        end
    end

    def destroy
      find_admin_forms
      if @pet_wall.destroy
        flash[:error] = "producto eliminado"
        redirect_to admin_forms_path
      end
    end

    def show
      find_admin_forms
      if @pet_wall.nil?
        flash[:error] = "Houston we are in troubles, please dont hack us."
        redirect_to root_path
      end
    end


    def update
        find_admin_forms
        if @pet_wall.update(admin_forms_params)
          redirect_to admin_form_path(params[:id])
        end
    end

    private

    def find_admin_forms
      @pet_wall = PetWall.find_by(id: params[:id])
    end

    #strong parameters
    def admin_forms_params
      params.require(:pet_wall).permit(:name , :breed , :size , :age , :type , :descriptions , :state , :image, :admission_date)
    end
end

app/controllers/adopters/adopter_controller.rb
class Adopters::AdopterController < ApplicationController
  before_action :authenticate_adopter!#autenticador se coloca en el controlador que quieras restringir

  def new_quertionary
    if current_adopter.score!=nil
      redirect_to root_path
    end
  end

  def create_quertionary
    puntaje = 0
    params.each do |key, value|
      if key[0..2].eql? "opt"
        puntaje = puntaje + value.to_i
      end
    end
    user = User.find_by(id: current_adopter.id)
    user.update(:score => puntaje)
    redirect_to root_path
  end

end

app/controllers/adopters/unlocks_controller.rb
class Adopters::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/adopters_questionary_controller.rb
class AdoptersQuestionaryController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create

  end

  def update
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def index
    
  end
end

app/controllers/pet_wall_users_controller.rb
class PetWallUsersController < ApplicationController

  before_action :authenticate_fundation!#autenticador se coloca en el controlador que quieras restringir
    def index
      if fundation_signed_in?
        @pet_wall_user= PetWallUser.where(user_id:current_fundation.id)
      end
    end

  
    private

    def find_pet_wall_user
      @pet_wall_user = PetWallUser.find_by(id: params[:id])
    end

    #strong parameters
    def pet_wall_users_params
      params.require(:pet_wall).permit(:pet_walls_id , :user_id , :score , :comments )
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def welcome
    if fundation_signed_in?
      @pet_wall= PetWall.where(user_id:current_fundation.id)
    else
      @pet_wall= PetWall.all
    end
  end

  def fundations
    redirect_to new_fundation_registration_path
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin_forms_helper.rb
module AdminFormsHelper
end

app/helpers/adopters/adopter_helper.rb
module Adopters::AdopterHelper
end

app/helpers/adopters_questionary_helper.rb
module AdoptersQuestionaryHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= current_adopter ? current_adopter : current_fundation ? current_fundation : nil
  end
end

app/helpers/pet_wall_users_helper.rb
module PetWallUsersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin_forms/_form.html.erb
<% form_name ||= "Manage" %>
<h1 class="text-center"><%=form_name %> friend </h1>
<%= form_for @pet_wall ,url: admin_forms_path, method:(form_name.downcase == 'edit' ? 'put' : 'post') do |f|%>
    <% if @pet_wall.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@pet_wall.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @pet_wall.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

    <div class="form-group">
      <%= f.label :name%>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :image%>
      <%= f.file_field :image, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :breed%>
      <%= f.text_field :breed, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :Size%>
      <select name="pet_wall[size]">
      <option value="1" selected="selected">Small</option>
      <option value="2">Medium</option>
      <option value="3">Big</option>
    </select>

    </div>

    <div class="form-group">
      <%= f.label :Age%>
      <%= f.number_field :age, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :Type%>
      <%= radio_button_tag(:pet,"dog") %>
      <%= label_tag(:pet_dog, "Dog") %>
      <%= radio_button_tag(:pet,"cat") %>
      <%= label_tag(:pet_cat, "Cat") %>

    </div>

    <div class="form-group">
      <%= f.label :descriptions%>
      <%= f.text_area :descriptions , class: "form-control" %>
    </div>


    <div class="form-group">
      <%= f.label :admission_date%>
      <%= f.date_select :admission_date, class: "form-control" %>
    </div>

    <%= f.submit "#{form_name} pet", class: "btn btn-primary" %>
    <a href="" class="btn btn-default"> Clear </a>
<% end %>

app/views/admin_forms/edit.html.erb
<div class="container4">
  <%= render "form" , form_name: params[:action].capitalize %>
</div>

app/views/admin_forms/index.html.erb
<div class="container1">
  <h1 class="text-center"> Our Friends </h1>
  <section class="row text-center admin_forms-controls">
      <a href="<%= new_admin_form_path %>" class="btn btn-default"> New friend </a>
  </section>
  <% @admin_forms.each do |af| %>
    <article class="pet">
      <ul class="list-unstyled">
        <div class="content_pet">
          <li class="admin_forms_name"><strong>Name: <%= af.name %></strong></li>
          <li class="admin_forms_name"><strong><%= image_tag af.image.thumb%></strong></li>
        </div>
        <div class="content_pet">
          <li class="admin_forms_name"><strong>Breed: <%= af.breed %></strong></li>
          <li class="admin_forms_name"><strong>Size: <%= af.size %></strong></li>
          <li class="admin_forms_name"><strong>Age: <%= af.age %></strong></li>
          <li class="admin_forms_name"><strong>Type: <%= af.type %></strong></li>
          <li class="admin_forms_name"><strong>Descriptions: <%= af.descriptions %></strong></li>
          <li class="admin_forms_name"><strong>State: <%= af.state %></strong></li>
          <li class="admin_forms_name"><strong>Admission_date: <%= af.admission_date %></strong></li>
          <a href="<%= admin_form_path(af.id) %>" data-method="delete" > <li class="btn_general">Delete </li></a>
          <a href="<%= edit_admin_form_path(af.id) %>" > <li class="btn_general">Edit </li></a>
          <a href="<%= admin_form_path(af.id) %>" ><li class="btn_general"> Show </li></a>
        </div>
      </ul>
    </article>

  <% end if @admin_forms.any? %>

</div>

app/views/admin_forms/new.html.erb
<div class="container_form">
  <%= render "form" , form_name: params[:action].capitalize %>
</div>

app/views/admin_forms/show.html.erb
<div id="adopter_view">
  <article class="pet">
    <ul class="list-unstyled">
      <li class="admin_forms_name"><p><%= @pet_wall.name %></p></li>
      <li class="admin_forms_name"><%= image_tag @pet_wall.image_url %></li>
      <li class="admin_forms_name"><strong>Breed: <%= @pet_wall.breed %></strong></li>
      <li class="admin_forms_name"><strong>Size: <%= @pet_wall.size %></strong></li>
      <li class="admin_forms_name"><strong>Age: <%= @pet_wall.age %></strong></li>
      <li class="admin_forms_name"><strong>Type: <%= @pet_wall.type %></strong></li>
      <li class="col-md-2"><a href="<%= pet_wall_path(@pet_wall.id) %>" data-method="delete" class="btn btn-default"> Delete </a></li>
    </ul>
  </article>
</div>

app/views/static_pages/welcome.html.erb
<div class="container">

    <section id="container1">
      <section id="bg">
        <aside class="">
          <h1>Best Friends</h1>
        </aside>
      </section>
      <img class="shadow" src="<%= image_path('sombra_bg_home.png') %>" alt="">

    </section>

    <section id="adopter_view">
      <% @pet_wall.each do |pw| %>

        <article class="pet">
          <ul class="list-unstyled">
            <div class="content_pet">
              <li class="admin_forms_name"><p><%= pw.name %></p></li>
              <li class="admin_forms_name"><%= image_tag pw.image_url %></li>
              <a href="<%= admin_form_path(pw.id) %>" > <li class="btn_general">Show </li></a>
            </div>
          </ul>
        </article>

      <%end if @pet_wall.any? %>
    </section>
</div>