config/routes.rb
Rails.application.routes.draw do



  get 'pet_wall_users/index'

  get 'pet_wall_users/show'

  get 'static_pages/welcome'

  devise_for :adopters, controllers: {
          sessions: 'adopters/sessions',
          passwords: 'adopters/passwords',
          registrations: 'adopters/registrations'
  }
  devise_for :fundations, controllers: {
          sessions: 'fundations/sessions',
          passwords: 'fundations/passwords',
          registrations: 'fundations/registrations'
  }
  get "fundations" => "static_pages#fundations"
  root to: 'static_pages#welcome'

  resources :admin_forms
  resources :pet_walls

  get "pet_wall_users" => "pet_wall_users#index"

  get "new_quertionary" => "adopters/adopter#new_quertionary"
  post "create_quertionary" => "adopters/adopter#create_quertionary"
end

app/models/adopter.rb
class Adopter < User
end

app/controllers/adopters/adopter_controller.rb
class Adopters::AdopterController < ApplicationController
  before_action :authenticate_adopter!#autenticador se coloca en el controlador que quieras restringir

  def new_quertionary
    if current_adopter.score!=nil
      redirect_to root_path
    end
  end

  def create_quertionary
    puntaje = 0
    params.each do |key, value|
      if key[0..2].eql? "opt"
        puntaje = puntaje + value.to_i
      end
    end
    user = User.find_by(id: current_adopter.id)
    user.update(:score => puntaje)
    redirect_to root_path
  end

end

app/controllers/adopters/confirmations_controller.rb
class Adopters::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/adopters/omniauth_callbacks_controller.rb
class Adopters::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/adopters/passwords_controller.rb
class Adopters::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/adopters/registrations_controller.rb
class Adopters::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/adopters/sessions_controller.rb
class Adopters::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/adopters/unlocks_controller.rb
class Adopters::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/adopters/adopter_helper.rb
module Adopters::AdopterHelper
end

app/views/adopters/adopter/new_quertionary.html.erb
<div id="container2">
  <h1 class="text-center">  Adopt questionary </h1>
  <%= form_tag create_quertionary_path, method: :post do %>
    <div class="form-group question">
      <label>1.</label>
      Wants a new best friend for ...
      <div class="radio"><label><input type="radio" name="opt1" value=5>You</label>
      <label><input type="radio" name="opt1" value=3>Family</label>
      <label><input type="radio" name="opt1" checked="checked" value=0>As present</label></div>
    </div>
    <div class="form-group question">
      <label>2.</label>
      In what type of residence do you live?
      <div class="radio"><label><input type="radio" name="opt2" value=5>House</label>
      <label><input type="radio" name="opt2" value=3>Apartment</label>
      <label><input type="radio" name="opt2" checked="checked" value=1>Room</label></div>
    </div>
    <div class="form-group question">
      <label>3.</label>
      How many hours a day do you estimate the pet will be alone?
      <div class="radio"><label><input type="radio" name="opt3" value=5>1-3</label>
      <label><input type="radio" name="opt3" value=3>4-5</label>
      <label><input type="radio" name="opt3" checked="checked" value=0>More than 5</label></div>
    </div>
    <div class="form-group question">
      <label>4.</label>
      Have you had a pet before?
      <div class="radio"><label><input type="radio" name="opt4" value=3>Yes</label>
      <label><input type="radio" name="opt4" checked="checked" value=0>No</label></div>
    </div>
    <div class="form-group question">
      <label>5.</label>
      Does anyone living with you (or you) be allergic to dog or cat hair?
      <div class="radio"><label><input type="radio" checked="checked" value=0 name="opt5">Yes</label>
      <label><input type="radio" name="opt5" value=3>No</label></div>
    </div>
    <div class="form-group question">
      <label>6.</label>
      Do you understand that adoption is a lifelong commitment?
      <div class="radio"><label><input type="radio" checked="checked" name="opt6" value=0>No</label>
      <label><input type="radio" name="opt6" value=2>Yes</label></div>
    </div>
    <div class="form-group question">
      <label>7.</label>
      Are you aware of the economic cost of keeping a pet?
      <div class="radio"><label><input type="radio" name="opt7" value=3>Yes</label>
      <label><input type="radio" name="opt7" checked="checked" value=1>No</label></div>
    </div>
    <div class="form-group question">
      <label>8.</label>
      Do you agree to a periodic visit to your home to verify the status of the adopted animal?
      <div class="radio"><label><input type="radio" name="opt8" value=5>Yes</label>
      <label><input type="radio" name="opt8" checked="checked" value=2>No</label></div>
    </div>
    <div class="form-group question">
      <label>9.</label>
      What do you want the pet for?
      <div class="radio"><label><input type="radio" name="opt9" value=5>Companionship</label>
      <label><input type="radio" name="opt9" checked="checked" value=2>Guard</label></div>
    </div>
    <div class="form-group question">
      <label>10.</label>
      Point out the care you and your family would be willing to give your new pet:
      <div class="checkbox"><label><input type="checkbox" name="opt10" value="4">Veterinary visits</label></div>
      <div class="checkbox"><label><input type="checkbox" name="opt11" value="5">Vaccination and vitamins</label></div>
      <div class="checkbox"><label><input type="checkbox" name="opt12" value="4">Daily walks</label></div>
      <div class="checkbox"><label><input type="checkbox" name="opt13" value="3">Use of collar with nameplate</label></div>
      <div class="checkbox"><label><input type="checkbox" name="opt14" value="5">Adequate food every day</label></div>
    </div>
    <div class="text-center form-group question">
      <button type="button" class="btn-lg btn btn-default">Clean</button>
      <button href="adopters_quertionary_path" type="submit" class="btn-lg btn btn-success">Save</button>
    </div>
  <% end %>
</div>